BBBB BBBBBBBBBB

BB BBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
            
        BBBBBB
    XXXXXX
BBBBB

XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    XXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Log in') XXXXX
    BBBBBBBBBBBBBB BBBB
    XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Log in') XXXXXXXXX
    XXXX
    XXX gettext(u"Don't have an account?")  XX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Sign up') XXXXXXXX
    XXX gettext(u'Forgot your password?')  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Reset it') XXXXXXXX
    BB BBBBBBBBBBBBBBBBBBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXX
    BBBBB
XXXXXXX
