BBBB BBBBBBBBBBBBB

BB BBBBBBBBB
  XXXX gettext(u'Sign in using') XXXXX
  XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBB BBBBBBBB BB BBBBBBBBB
      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBB BB BBBBBBBBXXXXXX BBBBXXXXXXXXXXXXXXXXXXXXXXX BBBBB BB BBB BBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXXXXXXXBBBBBXX
        XX XXXXXXBBBBBBBBBBBBBBBBBB BBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXX XXXXXXXX
          XX XXXXXXXXX XXX XXXXXXXXXXX
           gettext(u'Sign in with %(name)s') SSSS SS SSSS SSSSSSSS
        XXXX
      XXXXX
    BBBBBB
  XXXXX
BBBBB
